const apiMusicMaker = {
  getMusicMaker: () => {
    return [
      {
        id: 0,
        avatar:
          "https://avatar-ex-swe.nixcdn.com/singer/avatar/2018/07/19/8/1/6/a/1531989394829_600.jpg",
        stageName: "Suboi",
        role: "Rapper",
        singles: [
          {
            id: "su_troiCho",
            avatar:
              "https://photo-resize-zmp3.zmdcdn.me/w256_r1x1_jpeg/avatars/1/5/a/e/15ae72f637fd1d941a934b3edcf1ac39.jpg",
            title: "Trời Cho",
            stageName: "Suboi",
            type: "Single",
            genre: "Rap/HipHop",
            releaseDay: "",
            streamed: "2500",
            link: "",
            lyric: "",
          },
          {
            id: "su_doi",
            avatar:
              "https://static.tuoitre.vn/tto/i/s626/2016/03/10/suboi-doi-mv-1457581497.jpg",
            title: "Đời",
            stageName: "Suboi",
            type: "Single",
            genre: "Rap/HipHop",
            releaseDay: "",
            streamed: "3522",
            link: "",
            lyric: "",
          },
          {
            id: "su_dauThienHa",
            avatar:
              "https://bloganchoi.com/wp-content/uploads/2024/03/loi-bai-hat-dau-thien-ha-lyric-suboi-1-696x696.jpg",
            title: "Dâu Thiên Hạ",
            stageName: "Suboi",
            type: "Single",
            genre: "Rap/HipHop",
            releaseDay: "",
            streamed: "2862",
            link: "",
            lyric: "",
          },
        ],
        albums: [
          {
            id: 0,
            albumAvatar:
              "https://www.elle.vn/wp-content/uploads/2021/07/23/443917/suboi-va-album-no-ne-2.jpg",
            albumPerformer: "Suboi",
            albumName: "No Nê",
            releaseDay: "",
            tracks: [
              {
                id: "su_NoNe01",
                title: "Công",
                stageName: "Suboi",
                type: "Album - No Nê",
                genre: "Rap/HipHop",
                releaseDay: "",
                streamed: "",
                link: "",
                lyric: "",
              },
              {
                id: "su_NoNe02",
                title: "Cho Không",
                stageName: "Suboi",
                type: "Album - No Nê",
                genre: "Rap/HipHop",
                releaseDay: "",
                streamed: "",
                link: "",
                lyric: "",
              },
              {
                id: "su_NoNe03",
                title: "N-Sap?",
                stageName: "Suboi",
                type: "Album - No Nê",
                genre: "Rap/HipHop",
                releaseDay: "",
                streamed: "",
                link: "",
                lyric: "",
              },
              {
                id: "su_NoNe04",
                title: "Sickerrr",
                stageName: "Suboi",
                type: "Album - No Nê",
                genre: "Rap/HipHop",
                releaseDay: "",
                streamed: "",
                link: "",
                lyric: "",
              },
              {
                id: "su_NoNe05",
                title: "Best Friend",
                stageName: "Suboi",
                type: "Album - No Nê",
                genre: "Rap/HipHop",
                releaseDay: "",
                streamed: "",
                link: "",
                lyric: "",
              },
              {
                id: "su_NoNe06",
                title: "Bet On Me",
                stageName: "Suboi",
                type: "Album - No Nê",
                genre: "Rap/HipHop",
                releaseDay: "",
                streamed: "",
                link: "",
                lyric: "",
              },
              {
                id: "su_NoNe07",
                title: "Lava",
                stageName: "Suboi",
                type: "Album - No Nê",
                genre: "Rap/HipHop",
                releaseDay: "",
                streamed: "",
                link: "",
                lyric: "",
              },
              {
                id: "su_NoNe08",
                title: "Ngày Lại Ngày",
                stageName: "Suboi",
                type: "Album - No Nê",
                genre: "Rap/HipHop",
                releaseDay: "",
                streamed: "",
                link: "",
                lyric: "",
              },
              {
                id: "su_NoNe09",
                title: "Diều",
                stageName: "Suboi",
                type: "Album - No Nê",
                genre: "Rap/HipHop",
                releaseDay: "",
                streamed: "",
                link: "",
                lyric: "",
              },
              {
                id: "su_NoNe10",
                title: "Công (Dance Remix)",
                stageName: "Suboi",
                type: "Album - No Nê",
                genre: "Rap/HipHop",
                releaseDay: "",
                streamed: "",
                link: "",
                lyric: "",
              },
            ],
          },
        ],
      },
      {
        id: 1,
        avatar:
          "https://avatar-ex-swe.nixcdn.com/singer/avatar/2022/09/16/2/e/3/c/1663304448274_600.jpg",
        stageName: "Rhymastic",
        role: "Rapper/ Music Producer",
        singles: [
          {
            id: "rhym_Lac",
            avatar:
              "https://avatar-ex-swe.nixcdn.com/song/2022/06/22/2/2/2/d/1655865432491_640.jpg",
            title: "Lạc",
            stageName: "Rhymastic",
            type: "Single",
            genre: "RapHipHop",
            releaseDay: "",
            streamed: "",
            link: "",
            lyric: "",
          },
          {
            id: "rhym_Treasure",
            avatar:
              "https://photo-resize-zmp3.zadn.vn/w600_r1x1_jpeg/covers/6/d/6d9bfab656c9be37b3ef972b8c9dd291_1503659621.jpg",
            title: "Treasure",
            stageName: "Rhymastic",
            type: "Single",
            genre: "Pop",
            releaseDay: "",
            streamed: "",
            link: "",
            lyric: "",
          },
        ],
        albums: [
          {
            id: 1,
            albumAvatar:
              "https://i.scdn.co/image/ab67616d0000b273d98135e509a6271e6d1605a7",
            albumPerformer: "Rhymastic",
            albumName: "LOV6 (EP)",
            releaseDay: "",
            tracks: [
              {
                id: "rhym_Lov601",
                title: "Y6U",
                stageName: "Rhymastic",
                type: "Album - LOV6",
                genre: "RnB",
                releaseDay: "",
                streamed: "",
                link: "",
                lyric: "",
              },
              {
                id: "rhym_Lov602",
                title: "Lía La Lía Lo",
                stageName: "Rhymastic",
                type: "Album - LOV6",
                genre: "Pop",
                releaseDay: "",
                streamed: "",
                link: "",
                lyric: "",
              },
              {
                id: "rhym_Lov603",
                title: "Side Effects",
                stageName: "Rhymastic",
                type: "Album - LOV6",
                genre: "RnB/HipHop",
                releaseDay: "",
                streamed: "",
                link: "",
                lyric: "",
              },
              {
                id: "rhym_Lov604",
                title: "Ngổn Ngang",
                stageName: "Rhymastic",
                type: "Album - LOV6",
                genre: "RnB",
                releaseDay: "",
                streamed: "",
                link: "",
                lyric: "",
              },
              {
                id: "rhym_Lov605",
                title: "Vẫn Yêu",
                stageName: "Rhymastic",
                type: "Album - LOV6",
                genre: "RnB",
                releaseDay: "",
                streamed: "",
                link: "",
                lyric: "",
              },
              {
                id: "rhym_Lov606",
                title: "Thêm Đứa Nữa",
                stageName: "Rhymastic",
                type: "Album - LOV6",
                genre: "Electro-disco",
                releaseDay: "",
                streamed: "",
                link: "",
                lyric: "",
              },
            ],
          },
        ],
      },
      {
        id: 2,
        avatar:
          "https://pm1.aminoapps.com/6721/133a1fc95821719a9903e8188e872378217b1e63_hq.jpg",
        stageName: "MIN",
        role: "Singer",
        singles: [
          {
            id: "min_Ghen",
            avatar:
              "https://photo-resize-zmp3.zadn.vn/w600_r1x1_jpeg/covers/d/0/d05f9b3c87cf7ccda468174b28757489_1495770525.jpg",
            stageName: "KHẮC HƯNG x MIN x ERIK",
            title: "Ghen",
            type: "Single",
            genre: "Pop",
            releaseDay: "",
            streamed: "1500",
            link: "",
            lyric: "",
          },
        ],
        albums: [
          {
            id: 2,
            albumAvatar:
              "https://product.hstatic.net/1000304920/product/img_8111_fd368c181e0b461eba5c1b09c6626f84_master.jpg",
            albumPerformer: "MIN",
            albumName: "50/50",
            releaseDay: "",
            tracks: [
              {
                id: "min_505001",
                title: "",
                stageName: "",
                type: "",
                genre: "",
                releaseDay: "",
                streamed: "",
                link: "",
                lyric: "",
              },
            ],
          },
        ],
      },
      {
        id: 3,
        avatar: "https://cdn-www.vinid.net/ed96bcd6-touliver-1.jpg",
        stageName: "Touliver",
        role: "Dj/ Music Producer",
        singles: [
          {
            id: "tou_GetIt",
            avatar:
              "https://photo-resize-zmp3.zadn.vn/w600_r1x1_jpeg/cover/1/4/1/b/141b9f990d714085e3a23fd8a42be625.jpg",
            title: "Get It",
            stageName: "Touliver x Nimbia",
            type: "Single",
            genre: "Dance",
            releaseDay: "",
            streamed: "",
            link: "",
            lyric: "",
          },
        ],
        albums: [],
      },
      {
        id: 4,
        avatar:
          "https://yt3.googleusercontent.com/jd9_c5NiLJ1tXXwRpkDo1r-NqZ_IiXFJFAULwqQZrw_n4YRj0Omo4jTAMQFSm2u9PVc3AiZSgg=s900-c-k-c0x00ffffff-no-rj",
        stageName: "J.Sheon",
        role: "Singer",
        singles: [
          {
            id: "jshe_DontAsk",
            avatar: "https://i.ytimg.com/vi/tRa3fOlnN7k/maxresdefault.jpg",
            title: "Don't Ask (別問很可怕)",
            stageName: "J.Sheon",
            type: "Single",
            genre: "RnB Soul",
            releaseDay: "",
            streamed: "",
            link: "",
            lyric: "",
          },
        ],
        albums: [],
      },
      {
        id: 5,
        avatar:
          "https://i.scdn.co/image/ab6761610000e5eb3955d594fd646c2b77f2ae03",
        stageName: "Perfume",
        role: "Band",
        singles: [
          {
            id: "per_SpinningWorld",
            avatar:
              "https://i.scdn.co/image/ab67616d0000b273de342f1d1fc6c3de3f6e5d1e",
            title: "Spinning World",
            stageName: "Perfume",
            type: "Single",
            genre: "Electronic",
            releaseDay: "",
            streamed: "",
            link: "",
            lyric: "",
          },
        ],
        albums: [
          {
            id: 3,
            albumAvatar:
              "https://draw.acharts.net/cover/80760-54d08c7965c19-l.jpg",
            albumPerformer: "Perfume",
            albumName: "Level 3",
            releaseDay: "",
            tracks: [
              {
                id: "",
                title: "",
                stageName: "",
                type: "",
                genre: "",
                releaseDay: "",
                streamed: "",
                link: "",
                lyric: "",
              },
            ],
          },
        ],
      },
      {
        id: 6,
        avatar:
          "https://kenh14cdn.com/203336854389633024/2024/5/15/photo-2-1715757381263983732539.jpg",
        stageName: "BIBI",
        role: "Singer",
        singles: [
          {
            id: "bi_AnimalFarm",
            avatar:
              "https://images.genius.com/ea9cd6fef54ecdc755d6b10be33fda43.1000x1000x1.png",
            title: "Animal Farm (가면무도회)",
            stageName: "BIBI",
            type: "Single",
            genre: "Pop",
            releaseDay: "",
            streamed: "",
            link: "",
            lyric: "",
          },
        ],
        albums: [
          {
            id: 4,
            albumAvatar:
              "https://cdns-images.dzcdn.net/images/cover/e237cedbbecf26c383d6a3e240408644/0x1900-000000-80-0-0.jpg",
            albumPerformer: "BIBI",
            albumName: "Life is a Bi…",
            releaseDay: "",
            tracks: [
              {
                id: "",
                title: "",
                stageName: "",
                type: "",
                genre: "",
                releaseDay: "",
                streamed: "",
                link: "",
                lyric: "",
              },
            ],
          },
        ],
      },
      {
        id: 7,
        avatar:
          "https://cdn.tuoitre.vn/zoom/700_700/471584752817336320/2023/9/30/phan-manh-quynh-2-nvcc-1647595826560676316986-205-0-976-1473-crop-1696035354773707165885.jpg",
        stageName: "Phan Mạnh Quỳnh",
        role: "Musician/ Singer",
        singles: [
          {
            id: "pmq_SauLoiTuKhuoc",
            avatar:
              "https://photo-resize-zmp3.zmdcdn.me/w256_r1x1_jpeg/cover/e/d/0/7/ed0741228ad36870e13624120474e50a.jpg",
            title: "Sau lời từ khước",
            stageName: "Phan Mạnh Quỳnh",
            type: "Single",
            genre: "Pop/Ballad",
            releaseDay: "",
            streamed: "",
            link: "",
            lyric: "",
          },
        ],
        albums: [],
      },
      {
        id: 8,
        avatar: "https://avatarfiles.alphacoders.com/174/174632.jpg",
        stageName: "Eminem",
        role: "Rapper",
        singles: [
          {
            id: "em_KillShot",
            avatar:
              "https://upload.wikimedia.org/wikipedia/en/1/15/Eminem_Killshot.jpg",
            title: "KILLSHOT",
            stageName: "Eminem",
            type: "Single",
            genre: "Rap/HipHop",
            releaseDay: "",
            streamed: "",
            link: "",
            lyric: "",
          },
        ],
        albums: [
          {
            id: 5,
            albumAvatar:
              "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTwcAqv_T5ey2mfFEyLcXe3o7VASzb7K825OQ&s",
            albumPerformer: "Eminem",
            albumName: "Infinite",
            releaseDay: "",
            tracks: [
              {
                id: "",
                title: "",
                performer: "",
                genre: "",
                releaseDay: "",
                streamed: "",
                link: "",
                lyric: "",
              },
            ],
          },
          {
            id: 6,
            albumAvatar:
              "https://upload.wikimedia.org/wikipedia/en/b/b4/Encore_%28Eminem_album%29_coverart.jpg",
            albumPerformer: "Eminem",
            albumName: "Encore",
            releaseDay: "",
            tracks: [
              {
                id: "",
                title: "",
                stageName: "",
                type: "",
                genre: "",
                releaseDay: "",
                streamed: "",
                link: "",
                lyric: "",
              },
            ],
          },
          {
            id: 7,
            albumAvatar:
              "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSvzhz649VDzgSfhxy-x5KfU4JjggfTe_tEJz0bIbhd3-paHNprUKcJI3Fe6ud-7lx0PJk&usqp=CAU",
            albumPerformer: "Eminem",
            albumName: "The Eminem Show",
            releaseDay: "",
            tracks: [
              {
                id: "",
                title: "",
                stageName: "",
                type: "",
                genre: "",
                releaseDay: "",
                streamed: "",
                link: "",
                lyric: "",
              },
            ],
          },
          {
            id: 8,
            albumAvatar:
              "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQmZ08XRYRtFkYAF1Cl9h8PqjEi67SfPBY7dA&s",
            albumPerformer: "Eminem",
            albumName: "Relapse",
            releaseDay: "",
            tracks: [
              {
                id: "",
                title: "",
                stageName: "",
                type: "",
                genre: "",
                releaseDay: "",
                streamed: "",
                link: "",
                lyric: "",
              },
            ],
          },
          {
            id: 9,
            albumAvatar:
              "https://upload.wikimedia.org/wikipedia/en/6/60/Recovery_Album_Cover.jpg",
            albumPerformer: "Eminem",
            albumName: "Recovery",
            releaseDay: "",
            tracks: [
              {
                id: "",
                title: "",
                stageName: "",
                type: "",
                genre: "",
                releaseDay: "",
                streamed: "",
                link: "",
                lyric: "",
              },
            ],
          },
          {
            id: 10,
            albumAvatar:
              "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRrpMJozqst-MyDuXtBcQ6TYH3f_JrztdwTIIMfuw65eOdmnQhEv7hB3Dv4z743qk1rdyc&usqp=CAU",
            albumPerformer: "Eminem",
            albumName: "Revival",
            releaseDay: "",
            tracks: [
              {
                id: "",
                title: "",
                stageName: "",
                type: "",
                genre: "",
                releaseDay: "",
                streamed: "",
                link: "",
                lyric: "",
              },
            ],
          },
        ],
      },
    ];
  },
};

export default apiMusicMaker;
